# Servlet
server:
  port: 9092
  servlet:
    context-path: /ecommerce
  error:
    whitelabel:
      enabled: false

# Spring
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    out-of-order: true
    table: schema_version
  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 8
    name: eCommerceLocalCP
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true

# AWS Cognito
cognito:
  jwks-uri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_TJ1mx2GPs/.well-known/jwks.json
